<?php
# Automatically generated by package administrator.
# Please do not edit by hand!
global $GUIDGroupOf, $GUIDReverseOf;
$GUIDGroupOf = array(
0 => 'char',
1 => 'unit',
2 => 'item',
3 => 'npc',
4 => 'gameobject'
);
$GUIDReverseOf = array(
'char' => 0,
'unit' => 1,
'item' => 2,
'npc' => 3,
'gameobject' => 4
);
?>