<?php
# Automatically generated by package administrator.
# Please do not edit by hand!
global $TableInstanceFields;
$TableInstanceFields = array(
'char' => array('account','name','x','y','map','level','inventory_bag','model','online','visible','state','HP','MP','STR','DEX','CON','INT','WIS','CHA'),
'gameobject' => array('name','x','y','z','map','level','visible','model','mixhash'),
'item' => array('parent','item_type','item_template','item_count','item_variables','mixhash'),
'npc' => array('x','y','map','level','model','visible','state'),
'unit' => array('x','y','map','level')
);
?>