<?php
# Automatically generated by package administrator.
# Please do not edit by hand!
global $TableInstanceFields;
$TableInstanceFields = array(
'char' => array('account','name','x','y','map','level','inventory_bag','model','online','visible','state'),
'gameobject' => array('x','y','map','level','visible','model'),
'item' => array('parent','item_type','item_template','item_count','item_variables'),
'npc' => array('x','y','map','level','model','visible','state'),
'unit' => array('x','y','map','level')
);
?>